[tasks.build]
description = "Build all output"
run = { task = "build:src" }

[tasks."build:src"]
description = "Build the library"
run = "pnpm exec vite build"
depends = ["build:cem"]
sources = [
  "src/**/*",
  "svelte.config.js",
  "tsconfig.app.json",
  "tsconfig.svelte.json",
  "vite.config.ts",
]
outputs = ["dist/**/*"]

[tasks."build:cem"]
description = "Build the Custom Elements Manifest"
run = ["pnpm exec cem analyze", "pnpm oxfmt ./register-types"]
sources = ["src/**/*", "custom-elements-manifest.config.js"]
outputs = ["register-types/**/*", "custom-elements.json"]
depends = ["//tools/cem-plugin-dts:build", "//tools/cem-plugin-svelte:build"]

[tasks.check]
description = "Run all checks"
run = [{ task = "check:app" }, { task = "check:node" }, { task = "check:tests" }]

[tasks."check:app"]
description = "Type-check the source code"
run = "pnpm exec svelte-check --tsconfig ./tsconfig.app.json"
depends = ["build:cem"]
hide = true

[tasks."check:node"]
description = "Type-check configuration files"
run = "pnpm exec tsc -p tsconfig.node.json"
hide = true

[tasks."check:tests"]
description = "Type-check test files"
run = "pnpm exec svelte-check --tsconfig ./tsconfig.test.json"
depends = ["build:cem"]
hide = true

[tasks.test]
description = "Run all tests"
run = [{ task = "check" }, { task = "test:browser", args = ["--browser.headless", "--run"] }]

[tasks."test:browser"]
description = "Run component tests in-browser"
run = "pnpm exec vitest --config=vitest.browser.config.ts"
depends = ["playwright:install"]

[tasks."playwright:install"]
description = "Install playwright browser dependencies"
run = """
if [ "$CI" = "true" ]; then
  pnpm exec playwright install chromium-headless-shell --with-deps
else
  pnpm exec playwright install chromium --with-deps
fi
"""
hide = true

