monorepo_root = true

[monorepo]
config_roots = ["definitions/*", "hosts/*", "tools/*"]

[tools]
node = "24.14.0"
npm = "11.5.1"
pnpm = "11.6.0"

[deps.pnpm]
auto = true

[deps.husky]
auto = true
depends = ["pnpm"]
run = "pnpm exec husky"
outputs = [".husky/_"]

[tasks.format]
description = "Run formatter on all files"
run = "pnpm exec oxfmt"

[tasks."format:check"]
description = "Run formatter on all files"
run = "pnpm exec oxfmt --check"

[tasks.test]
description = "Check formatting on all files"
run = [{ task = "format:check" }]

[tasks."husky:pre-commit"]
description = "Called by `husky` on pre-commit"
run = "pnpm exec lint-staged"
hide = true

[tasks.changeset]
description = "Create a changeset to add to the changelog"
run = "pnpm exec changeset"

[tasks."changeset:version"]
description = "Apply pending changesets"
run = "pnpm exec changeset version"
depends_post = ["format"]
hide = true

[tasks."changeset:release"]
description = "Publish a release using `changesets`"
run = "pnpm exec changeset publish"
depends = ["//tools/...:build"]
hide = true
